[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

# API proxy rule for VueFinder
[[redirects]]
  from = "/api/vf"
  to = "/.netlify/functions/vf"
  status = 200
  force = true

# SPA fallback rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

# Image CDN configuration
[images]
  remote_images = [ "https://lumencanvas.netlify.app/media/.*" ]

# Redirect for thumbnail service
[[redirects]]
  from = "/imgcdn/*"
  to = "/.netlify/images?url=/media/:splat&w=320&h=320&fit=cover"
  status = 200 