version: '3.8'

services:
  # Development configuration (HTTP/WS)
  yjs-server-dev:
    build: .
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
      - PORT=1234
      - ENABLE_TLS=false
    restart: unless-stopped
    container_name: yjs-server-dev

  # Production configuration (HTTPS/WSS)
  yjs-server-prod:
    build: .
    ports:
      - "443:443"
    environment:
      - HOST=0.0.0.0
      - PORT=1234
      - TLS_PORT=443
      - ENABLE_TLS=true
      - TLS_CERT=/certs/cert.pem
      - TLS_KEY=/certs/key.pem
    volumes:
      - /path/to/your/ssl/certs:/certs:ro
    restart: unless-stopped
    container_name: yjs-server-prod
    profiles:
      - production

  # Behind reverse proxy (recommended for production)
  yjs-server-proxy:
    build: .
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
      - PORT=1234
      - ENABLE_TLS=false
    restart: unless-stopped
    container_name: yjs-server-proxy
    profiles:
      - proxy

# Uncomment if using Redis
# volumes:
#   redis_data: 